version: '3.1'
services:
  calrecall-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - calrecall-redis
    environment:
      - REDIS_URL=redis://calrecall-redis:6379
      - NODE_ENV=development
    env_file:
      - .env
  
  calrecall-worker:
    build: 
      context: .
      dockerfile: Dockerfile    
    command: npm run dev:worker
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - calrecall-redis
    environment:
      - REDIS_URL=redis://calrecall-redis:6379
      - NODE_ENV=development
    env_file:
      - .env
    
  calrecall-redis:
    image: redis:6.2    
    ports:
      - "6379:6379"
